from __future__ import annotations

FREQUENCY_STEP_HZ = 500
MIN_FREQUENCY_HZ = 500
MAX_FREQUENCY_HZ = 20000

TARGET_FREQUENCIES_HZ = list(range(MIN_FREQUENCY_HZ, MAX_FREQUENCY_HZ + FREQUENCY_STEP_HZ, FREQUENCY_STEP_HZ))

DEFAULT_WATERFALL_HISTORY = 240
